### ISSUE TITLE
SQL Server Filtered Indexes Not Picked Up Properly

### ISSUE THREAD

**Issue by NeilN1** [wise-coders/dbschema#104]
Latest version of DbSchema.

Database has:
CREATE UNIQUE NONCLUSTERED INDEX [IX_Contact_MemberId] ON [dbo].[Contact]
(
	[MemberId] ASC
)
WHERE ([MemberId] IS NOT NULL)

Model has:
CREATE UNIQUE  INDEX IX_Contact_MemberId ON MOBILECRM.dbo.Contact ( MemberId );

The WHERE clause is not picked up.

**Comment by wise-coders** [comment]
Hello,
We will have a beta version ready right tomorrow morning, with the fix:
https://dbschema.com/beta.php
Please let me know if this works fine.

**Comment by NeilN1** [comment]
@wise-coders Build 230522.

I refreshed the table and it said the schemas were identical. Dropped index, refreshed, created index, refreshed, and I still get:

CREATE UNIQUE  INDEX IX_Contact_MemberId ON MOBILECRM.dbo.Contact ( MemberId );
GO

**Comment by wise-coders** [comment]
Do you get the same if you start a fresh model by reverse engineering the schema from the database?
