### ISSUE TITLE
Float SqlEditor InActive

### ISSUE THREAD

**Issue by Bsplesk** [wise-coders/dbschema#106]
Windows 10/DbSchema 9.3.0
Open SqlEditor (Ctrl+E) -->  Right Click Tab SqlEditor --> Float  --> It is not possible to enter/edit the text of the query.

[screenshot](https://i.imgur.com/AOSM6HA.png)

**Comment by wise-coders** [comment]
Issue will be fixed in the next release.

**Comment by Bsplesk** [comment]
@wise-coders 
incorrect starting window size of the floating window (Linux Gnome, Wayland, See screenshot).
[Linux/WayLand](https://i.imgur.com/9u6Xhxl.png)

**Comment by wise-coders** [comment]
The issue will be fixed in the next release.
