### ISSUE TITLE
Please let me know what was worked on in each Beta

### ISSUE THREAD

**Issue by Psyclo1** [wise-coders/dbschema#107]
This is a general request rather than a specific bug.  I regularly check the Beta page for the latest version of DbSchema.  However, I can't tell what was done.  Please include something like a "what changed" list as a file to download/view.  I've seen a lot of these from various software products that are added to on the top, so they read newest to oldest.  So, you would have 250513 with a list of what was worked on and maybe a status (working on logical model entity edit dialog adding new button "xyz", functionality not complete)  This would let me direct my beta testing to ensure I'm looking in the right places.

**Comment by wise-coders** [comment]
Will be fixed in the next release.
