### ISSUE TITLE
DbShell transfer command not work, Message "Error: Invalid connection"

### ISSUE THREAD

**Issue by git4wht** [wise-coders/dbschema#109]
1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.4.0 build 230525
Ubuntu 22.04.2 LTS

3. The steps to reproduce this issue
transfer table from sourcecon using select * ..;
get error message "Error: Invalid connection ****"
zhe script is ok on dbshell-1.3.2

**Comment by wise-coders** [comment]
Hello,
Please evaluate the beta release from today:
https://dbschema.com/beta.php
It has improvements related to the data transfer.
