### ISSUE TITLE
Foreign Key Routing Notification

### ISSUE THREAD

**Issue by kasiasulowska** [wise-coders/dbschema#110]
Hi,

I am facing the problem with foreign key routing. In one of my layouts I have 203 tables and the 'foreign key routing notification' appears. 

![image](https://github.com/wise-coders/dbschema/assets/136348794/49e4befd-5c3a-45e2-9a3a-cdd998d9c177)

Is there a way of changing the routing options to draw all of the relations? Any ideas? I do not want to move manually all of the tables in the layout... 
I found this topic: https://github.com/wise-coders/dbschema/issues/24 but I'm not a CSS expert so I don't know if it possible to change any properties of key routing in the code.
DbSchema version: 9.4.0
OS: win 11

Thanks for any hints!

**Comment by wise-coders** [comment]
Unfortunately we don't have a solution for this issue. In most cases, having more space between tables solves this issue.
