### ISSUE TITLE
Triggers are not shown in Triggers in table tree

### ISSUE THREAD

**Issue by mkocztorz** [wise-coders/dbschema#115]
1. Please check DbSchema Help / Output logs for errors.
none

2. Please include the DbSchema version, operating system and used database
9.4.2 build 230925
MacOS 13.0.1 (22A400)
Postgres schema

3. The steps to reproduce this issue
Right click on triggers in table and create a trigger. 

Trigger is created in the Triggers for schema, but not in the table. 
In the file table param is missing on trigger node. If I add it manually to the file, trigger is shown in the table triggers again.

**Comment by wise-coders** [comment]
Will be fixed in the next DbSchema release.
