### ISSUE TITLE
Can't display the table fields

### ISSUE THREAD

**Issue by max529** [wise-coders/dbschema#116]
I have the current table inside a mariadb instance

```sql
CREATE TABLE `core.user` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Firstname` varchar(255) NOT NULL,
  `Lastname` varchar(255) NOT NULL,
  `Username` varchar(255) NOT NULL,
  `Password` text NOT NULL,
  `Token` varchar(255) NOT NULL,
  `Picture` varchar(255) NOT NULL,
  `CreatedDate` datetime NOT NULL,
  `UpdatedDate` datetime NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
````

The parser can load the table but can't load the fields for the table. I think, it's because the table name includes a dot but I'm not sure. I checked the ouput logs but there is no error.

Version 

- DbSchema 9.4.2 build 231015 
- windows 10 
- MariaDB 10.4.27

**Comment by wise-coders** [comment]
You are right, the issue is related to dot in the table name.
This is a special case, and it will take some time for us to fix it.
You should avoid using dots in the table name.
