### ISSUE TITLE
What's DBSchema's license?

### ISSUE THREAD

**Issue by GetPsyched** [wise-coders/dbschema#117]
I've searched the website a fair bit and the closest thing I've found to the license is the [EULA](https://dbschema.com/legal/eula.pdf). I wanted to ask if this is it or is there something else?

Asking since I'm packaging this for [nixpkgs](https://github.com/NixOS/nixpkgs), I'll need a license name for the same.

**Comment by wise-coders** [comment]
I'm wondering if the license should have a name. The license can be any text. The named licenses are some pre-defined terms.
If I look other products, like IntelliJ, they also don't have a name for their license.

**Comment by GetPsyched** [comment]
Yeah, not having a named license is totally fine. I just wanted to confirm this before adding the package to nixpkgs as it will require  me to create a custom license for DbSchema.
