### ISSUE TITLE
zoom in shortcut

### ISSUE THREAD

**Issue by omniapp** [wise-coders/dbschema#12]
Hi,
using a us keyboard with french macos system, the command+ shortcut doesnt work. the command-- and command-0 are working well

regards
 Hervé

**Comment by wise-coders** [comment]
Issue fixed, the fix will be available in the next minor release.

**Comment by Qwerios** [comment]
This does not appear to be fixed in version 8.2.9 (MacOS 10.15.3, Java 1.8.0_152). 
Standard US keyboard layout. Zoom out (Meta -) and 100% (Meta 0) do work but zoom in (Meta +) does not.

According to your own changelog this was last fixed in 8.2.0 in October 2019.

**Comment by wise-coders** [comment]
Could you please test with the current kit from website from today ? Is still version 8.2.9 but a higher build number 200421 or higher. I tested it on MacOS Mojave 10.14.6 and works fine.

**Comment by omniapp** [comment]
Hi,

Still not working, works with the + on the numerical keyboard.

MacOSX Mojave, French localisation English us keyboard


Bien à vous,
Hervé Lemaitre - OmniApp
‭01 83 64 57 98‬


Le 23 avril 2020 à 20:43:02, Wise Coders (notifications@github.com) a écrit:

Could you please test with the current kit from website from today ? Is still version 8.2.9 but a higher build number 200421 or higher. I tested it on MacOS Mojave 10.14.6 and works fine.

**Comment by Qwerios** [comment]
Updated from build 200330 to 200422. Still no working zoom in. Both on macbook keyboard or external keyboard.

**Comment by wise-coders** [comment]
We added one more fix in current build 200427. I think the issue is related to localization. Let's see if this fix does help.

**Comment by omniapp** [comment]
Nop not working, and we lost the + on the numerical pad that worked in the last version. Same player play again :o)
Still French localisation, English us keyboard

Bien à vous,
Hervé Lemaitre - OmniApp
‭01 83 64 57 98‬


Le 27 avril 2020 à 20:41:10, Wise Coders (notifications@github.com) a écrit:

We added one more fix in current build 200427. I think the issue is related to localization. Let's see if this fix does help.

**Comment by Qwerios** [comment]
I've updated to 200427 but still no working zoom in key. Also tried the numerical pad keys and no zoom in there either. Zoom out does work consistently.

**Comment by Qwerios** [comment]
Would it be an idea to re-open this issue?

**Comment by Qwerios** [comment]
Updated to 8.2.10 build 200506 today. No working zoom in keybind for Mac

**Comment by wise-coders** [comment]
Hello,

Thank you for reporting this issue. I have tested on a MacBook Pro, first I added a French keyboard ( QUERTY ).
The layout as in this image:  [1] https://medium.com/@ambroisemaupate/from-azerty-to-qwerty-1a9b294040f6

Pressing Command + ( I had to keep also the shift down, command and second key on the right, the one with = and + ) and zoom in works fine

Pressing Command - ( the minus is just near delete ) also works fine

I used DbSchema 8.2.10 to test this.
If this does not work for you, can you please help me to reproduce this issue ? Which keyboard layout should I add to my Mac and which combination of keys are needed ?
My default keyboard is like this: [2] https://en.wikipedia.org/wiki/File:KB_Germany.svg

Best regards,
 Dragos Pruteanu

--
 DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
 Email: support@dbschema.com - Web: [3] http://dbschema.com/

--

[1] https://medium.com/@ambroisemaupate/from-azerty-to-qwerty-1a9b294040f6
[2] https://en.wikipedia.org/wiki/File:KB_Germany.svg
[3] http://www.example.com/

**Comment by omniapp** [comment]
Hi

Did some new tests here :

I’m on a MacBook Pro 15, qwerty us keyboard


or


The Mac is configured as French :



And keyboard as abc (allow accent shortcuts) :



Tested today on 8.2.10 : 

Command 0 and command - works on keyboard
Command + (but = for real) don’t work on keyboard
Command - work on numeric pad
Command + and command 0 don’t work on numeric pad

A precedent version use to work on numeric pad, check the history.

Is it javafx under the hood ?

Bien à vous,
Hervé Lemaitre - OmniApp
‭01 83 64 57 98‬


Le 12 mai 2020 à 12:25:14, Wise Coders (notifications@github.com) a écrit:

Hello,

Thank you for reporting this issue. I have tested on a MacBook Pro, first I added a French keyboard ( QUERTY ).
The layout as in this image:  [1] https://medium.com/@ambroisemaupate/from-azerty-to-qwerty-1a9b294040f6

Pressing Command + ( I had to keep also the shift down, command and second key on the right, the one with = and + ) and zoom in works fine

Pressing Command - ( the minus is just near delete ) also works fine

I used DbSchema 8.2.10 to test this.
If this does not work for you, can you please help me to reproduce this issue ? Which keyboard layout should I add to my Mac and which combination of keys are needed ?
My default keyboard is like this: [2] https://en.wikipedia.org/wiki/File:KB_Germany.svg

Best regards,
Dragos Pruteanu

--
DbSchema - Wise Coders GbmH
82256 Fürstenfeldbruck bei München
Email: support@dbschema.com - Web: [3] http://dbschema.com/

--

[1] https://medium.com/@ambroisemaupate/from-azerty-to-qwerty-1a9b294040f6
[2] https://en.wikipedia.org/wiki/File:KB_Germany.svg
[3] http://www.example.com/
