### ISSUE TITLE
It is difficult to click to the arrow in the generated html/svg-file

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#123]
Description:
It is difficult to click to the arrow in the generated html/svg-file.
For better UX/UI, it is usually recommended to do not force a user to hover over (or mouse click to) such a tiny areas.
Here on the video you can see the mouse hover over an empty space in the back of the arrow doesn't react on mouse hover and mouse click.

https://github.com/user-attachments/assets/afbf424c-a7c5-4201-b6c4-ce50232f91f8

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.6.0 build 240615
Windows 10
Postgres 16

3. The steps to reproduce this issue

- generate schema using menu: Layout -> Export HTML5/MD/PDF Documentation
- open the result html/svg-file in browser
- enlarge the clickable area of elements of a generated html/svg-file
- mouse hover near the small arrow of a column of any table with a foreign key
- notice that only the tiny contour of the arrow is clickable

Ideally, the background of this arrow should also be clickable.

**Comment by wise-coders** [comment]
We will include a fix for this issue into the next release.
