### ISSUE TITLE
Turn off the notification about available updates

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#124]
When I open the application, it shows the notification about available updates:
![изображение](https://github.com/user-attachments/assets/4d16ded4-a498-4d95-bda6-9589db13905f)

I realize that software updates are important.
But for some reason, a user may want to keep using some specific version and turn off the notification about available updates.

In settings, I only found the option "Show Messages about Renewal", but setting it to false doesn't do what I want.
Ideally, it would be nice to add some additional option for that, or make use of the mentioned option.

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.6.0 build 240615
Windows 10
Postgres 16

3. The steps to reproduce this issue
- install the old version: 9.6.0
- open the application
- try to set false for the option "Show Messages about Renewal"
- reopen the application

**Comment by wise-coders** [comment]
Please use the option Help / Software Updates for this.
The option from the settings menu is for renewing the license. We will change the option text for this, making it more clear.

**Comment by ask9** [comment]
Oops! Sorry, I didn't notice that menu item. Thanks!

**Comment by ask9** [comment]
I set this option to Never and it doesn't work.
The notification is still shown on each statup.

**Comment by wise-coders** [comment]
This will be fixed in the next DbSchema release.
