### ISSUE TITLE
GitHub Actions Integration?

### ISSUE THREAD

**Issue by nelsonic** [wise-coders/dbschema#125]
Greetings @wise-coders 👋 
Our company has a `DbSchema` license and we are hoping to integrate your schema visualiser (HTML output) into our `GitHub Actions` (CI) so that we can create an (_internal_) Docs page for our `ERD`. 
Our reading of your Support page: https://dbschema.com/support.html
<img width="915" alt="image" src="https://github.com/user-attachments/assets/96ec8ea1-5798-4894-9f66-ba3def6ad268">

Is that it's possible to run `DbSchema` _headless_. ✅ 
But our **Question** is: can we run it _headless_ on `GitHub CI` in a workflow? :octocat: 🤖 🤞 
If it's doable do you have any precedent and ideally _instructions_ for setting it up? 📝 

Thanks in advance. 🙏

**Comment by nelsonic** [comment]
Yeah, going to give that malware a pass @tonywk https://github.com/LizardByte/Sunshine/issues/3100 but thanks. 👌

**Comment by wise-coders** [comment]
It should work to run DbSchema in headless mode, as described there. DbSchema is a Java application. We didn't test in a GitHub CI. Just give it a try.

**Comment by nelsonic** [comment]
@wise-coders thanks for the quick reply. 👌 
We'll give it a try now. 🧑‍💻 🤞
