### ISSUE TITLE
Exclude from layout multiple objects when selecting them in a tree of objects

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#128]
Is it possible to remove multiple object (film and film_category) when selecting them from a tree?
Sometimes it is easier for a user to do that from a list of objects rather than search and select them in a diagram.
Now only one of them is deleted.

https://github.com/user-attachments/assets/45a92516-dcb3-4aaa-99f6-7e81aebc04c9

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.6.0 build 240615
Windows 10
Postgres 16

3. The steps to reproduce this issue

**Comment by wise-coders** [comment]
The ticket will be fixed in the next release
