### ISSUE TITLE
Group Callout Location upon Layout | Auto Arrange Tables

### ISSUE THREAD

**Issue by spARXman** [wise-coders/dbschema#13]
DbSchema 8.2.7 build 200205

The location of a group's callout is revised each time the user invokes 'Layout | Auto Arrange Tables'

**Comment by wise-coders** [comment]
I tested this and it seems there is only a small move of the position. 
So I consider I couldn't reproduce this issue.
May I ask for a sample screenshot or a sample public project file to reproduce this issue ? Eventually you can send it on our email ( see the contacts on website ).

**Comment by spARXman** [comment]
Please try to ‘Auto Arrange’ a few times repeatedly.
