### ISSUE TITLE
Add button 'Copy' to copy the selected connection in "Manage connections" window

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#130]
It would be nice to have a button "Copy" in a window "Database connections" from menu "Connections" -> "Manage Connections".
Pressing it, a new copy of the selected connection appears in the list of connections with the all same setting of the connection.
After that, user can do some brief changes (change connection name, database, etc) which is usually easier than fill it from scratch.

Now, when I need to create a similar connection, I have to create a new connections and fill all the options (including user password with many symbols and special charaters) and it is a bit slow and boring.

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.6.0 build 240615
Windows 10
Postgres 16

3. The steps to reproduce this issue

**Comment by wise-coders** [comment]
The ticket will be implemented in the next release.
