### ISSUE TITLE
Add hotkey F5 to refresh schema

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#133]
Refreshing a schema is used acitvely in the application.
It is not convenient to click everytime to the small icon.
I suggest to add a hotkey for that action (for example, F5).
Also consider to change this hotkey somewhere in settings (this can be postponed with low priority).

![изображение](https://github.com/user-attachments/assets/a646eb7e-dda0-4bcc-9f9e-57aefcc245a6)

**Comment by wise-coders** [comment]
We can do this. But we can only add it to the option in the Schema menu, which is showing also a dialog to choose the schemes. This would be an extra click. Is this fine?

**Comment by ask9** [comment]
Yes, it is OK.

1. Additionally, instead of the extra click, can you handle "Enter" on keyboard as a user clicked OK button to confirm default chekcboxes in this dialog box? Now it doesn't work in this way.

2. I also do not understand the difference in behaviour between the Refresh-icon on the toolbar and the menu item you suggest to use.

**Comment by wise-coders** [comment]
If I press enter on Windows in the schema selection dialog, it triggers the Ok button and closes the dialog. Is this the dialog you are looking for?
The option in the menu shows additionally to the button in toolbar a schema selection dialog. The option in the toolbar is the same as clicking Ok in the schema selection dialog.

**Comment by ask9** [comment]
Yes. Thank you.
