### ISSUE TITLE
An error occurs on Refresh if the database was recreated while the application is running

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#134]
I recreate my database from sql-dump and then I refresh its schema in application.
On the first refresh, the exception occured (seems like some issue with connection to database takes place).
I expect this case to be handled seamlessly for a user (reconnect automatically "under the hood" without frighten a user with exceptions and additional mouse click and repeated Refresh of the schema).

![0000003899](https://github.com/user-attachments/assets/24af6af8-d9e6-466b-9be7-1a0c8037f0cf)

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
Windows 10
DbSchema 9.6.2 build 240907
Windows 10
Postgres 16

3. The steps to reproduce this issue
- execute the bat-file from archive: [recreate_database.zip](https://github.com/user-attachments/files/16928549/recreate_database.zip) to create sample database (adjust connection properties in the bat-file first)
- create schema from this database in DbSchema
- execute bat-file again to recreate all the objects in the database (the database will be dropped and created again from scratch)
- refresh schema in DbSchema (press F5 hotkey)

Expected: no error. no any changes in schema (if some changes would be made, they should be applied to the schema)
Actual: an error occurs (see the screenshot). Additional refresh needed to complete the refresh process.

**Comment by wise-coders** [comment]
Thank you for sending the script.
The error is issued by the PostgreSQL JDBC driver. I assume it holds a reference to the dropped schema.
We cannot hide the error, as automatically connecting again may lead to issues with other databases and other use cases.
If I am right, for now you have to press two times the refresh button ( first time will get the error, next time will work ). I think we should leave with this.
