### ISSUE TITLE
Context menu of one selected element and multiple selected elements is different

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#137]
I want to exclude some objects from schema using context menu.
I select a few of them and perform right click.
There is no item "Exclude from layout" in the context menu.
The overall list of items differs.

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.6.2 build 240928
OpenJRE 21.0.4
Windows 10
Postgres 16

3. The steps to reproduce this issue

https://github.com/user-attachments/assets/9091e105-18a3-4e57-affb-8520ceca49f6

**Comment by wise-coders** [comment]
May I ask, did you have a PRO license or is a Community Edition?
I am getting a different menu. There should be a menu item 'Drop item' from the schema.
It is not possible to exclude a table from a schema, but only to drop it.

![image](https://github.com/user-attachments/assets/f8937f26-8308-4a9d-9ec2-cff52b4deef2)

**Comment by ask9** [comment]
Hello. I have pro version.
Open a list of tables in **Layout** node, not in Schemas -Tables - Table.

**Comment by wise-coders** [comment]
I got it now. And you wish to have the 'Drop item' option there, right? 
I am not sure if this is a good decision. I think we should allow dropping it only from the schema menu.

**Comment by ask9** [comment]
> And you wish to have the 'Drop item' option there, right?

No, I don't. 
I feel misunderstanding between us.
I wish to add the item "Exclude from layout" in context menu of  multiple selected items for objects witin "Layout"-node.

![img1](https://github.com/user-attachments/assets/5423c6d7-d0d0-4cf7-882e-d152980ccf4d)

**Comment by wise-coders** [comment]
We will add a fix for this in the next release and beta update.
