### ISSUE TITLE
Suggestion: Auto Layout creation

### ISSUE THREAD

**Issue by paddelia1** [wise-coders/dbschema#138]
Hello,
For large models, it would be helpful to automatically generate layouts.
Example, I have 3000 tables in my main layout. I organize the model by areas, one layout per area.
If I can ask the software to auto create layouts from a list of strings to search for in the table names, that would save a lot of time.
Example, I give this list, Customer, Orders, Inventory, Invoices, Reports, Cases, Location
the software will search for groups of tables having this string in their names and create layout for these groups.
Ideally, I would like an option to create the layout with all non-key columns hidden.
Lastly when you have many layouts, the pull-down has a little rectangle at the bottom instead of a text.
Thanks

**Comment by wise-coders** [comment]
Currently, the layout dialog has a search filter. Creating a new layout and filtering makes adding the tables to the layout pretty easy.
