### ISSUE TITLE
Add colors in a list of groups

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#139]
I suggest to add feature to highlight automatically the name of a group in a list of groups when choosing a group for a table.
For example, film-group has green color, so the item in a list should also be colored with that color.
It makes it easier to find an appropriate group for a table when the list of groups is long.
Hope it is possible in Java.

![0000004593](https://github.com/user-attachments/assets/8974a834-7225-4515-bc85-fc51d0316578)

**Comment by wise-coders** [comment]
The feature will be implemented in the next release.
