### ISSUE TITLE
Procedures and Functions listed twice, in wrong folders.

### ISSUE THREAD

**Issue by dredev89** [wise-coders/dbschema#14]
DbSchema version: 8.2.7 build 200130
Operating system: Windows 10 Pro (10.0.17134 build 17134)
Used database: SQL Server 2016 Developer Edition

The steps to reproduce this issue:
1) Start new project
2) Connect To Database
3) Using the Database Connection Dialog: connect to an existing database (using Native Driver - Database Authentication)
4) Check a schema and all of the objects inside (Tables, Views, Procedures, Functions, ...)
5) After the procedure is completed: in the Project view, look at the folders Procedures and Functions. They containt the same quantity of objects, i.e. all the user functions and procedures in both of the folders.

I was expecting the User Defined Functions to be under the Functions folder and the stored procedures under the Procedures folder, separately.

![Procedures and Functions](https://user-images.githubusercontent.com/16489972/74859015-899ff880-5346-11ea-96a8-803e5a886bd0.PNG)

**Comment by wise-coders** [comment]
Could you please try to delete the folder .DbSchema from C:\Users\<YourUser> ?
This will delete all cached settings. Connecting to SQLServer you have to choose another database and then again SQLServer, so the driver is downloaded again.
Than try again to reverse engineer the schema. Does this look better ?
If the issue still persist we will test in detail. We are using the queries configured in Project / Settings / Reverse engineer to grab the procedures and functions. Eventually you can execute them in the SQL Editor.

**Comment by dredev89** [comment]
> Could you please try to delete the folder .DbSchema from C:\Users<YourUser> ?
> This will delete all cached settings. Connecting to SQLServer you have to choose another database and then again SQLServer, so the driver is downloaded again.
> Than try again to reverse engineer the schema. Does this look better ?
> If the issue still persist we will test in detail. We are using the queries configured in Project / Settings / Reverse engineer to grab the procedures and functions. Eventually you can execute them in the SQL Editor.

**Comment by dredev89** [comment]
> Could you please try to delete the folder .DbSchema from C:\Users<YourUser> ?
> This will delete all cached settings. Connecting to SQLServer you have to choose another database and then again SQLServer, so the driver is downloaded again.
> Than try again to reverse engineer the schema. Does this look better ?
> If the issue still persist we will test in detail. We are using the queries configured in Project / Settings / Reverse engineer to grab the procedures and functions. Eventually you can execute them in the SQL Editor.

Sorry, I closed the issue by accident.

I tried to follow the instructions, but the result is not changing.
I also tried to force manually the donload of the drivers, still same result.
![download drivers](https://user-images.githubusercontent.com/16489972/74938364-28cbfb00-53ee-11ea-8027-b5cc8532ab94.PNG)

I tried to execute the queries under Project/Settings/Reverse Engineering and they seems to work fine: the one for Procedure retrieves the name of just the stored procedures, the one for Functions the name of just the user defined functions.
![scripts](https://user-images.githubusercontent.com/16489972/74938492-6b8dd300-53ee-11ea-91fb-4d2936f2bb50.PNG)

**Comment by dredev89** [comment]
I also tried to 
1) uninstall dbschema
2) delete the folder .DbSchema from C:\Users\<YourUser>
3) reboot 
4) re-install
but the issue still persists.
When opening dbschema the first time after re-installing it, I found my Database Aliases already filled in, so I'm wondering if I should delete other files/folders too.

Thank you.

**Comment by wise-coders** [comment]
Issue is fixed in version 8.2.8, currently available on website. Please reopen the issue if this does not work as expected.
