### ISSUE TITLE
Create virtual foreign key when pressing Ctrl during drag & drop

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#140]
I suggest to add feature: if user press and don't release the Ctrl-key on a keyboard and drag & drop a column, the virtual foreign key is created (or the corresponding checkbox is set automatically).
It will make it easier to create virtual FK (avoid additional click) especially when you have to create many-many virtual FK.

https://github.com/user-attachments/assets/42b1498c-dd74-428d-9d34-538f039744fc

**Comment by wise-coders** [comment]
Features like this won't be known for the other users, as it is difficult to document and present this trick for the other users.

**Comment by ask9** [comment]
If the problem is only about informing users, it could be fixed using other methods.
For example, showing "Tips of the day" for a user or simply add the explanation of this feature to documentation in a chapter with list of all hotkeys available in application.

The example of "Tips of the day" in your application:

![0000004732](https://github.com/user-attachments/assets/622af38d-8a01-4169-a8d4-85203a40e3a9)

Using modifier keys (Ctrl, Alt, Shift) when performing some action is quite common in many applications and enriches the application with additional flexibility in daily use.
For example, in Windows, drag & drop in explorer moves the file and the same drag & drop with pressed Ctrl-key modifier copies the file.
Of course, user can copy file without this modifier, but it makes it slighly longer and not so convenient.
If the user doesn't aware of copying files using Ctrl + Drag & Drop, it is his problem :)

I have got a database with many tables and zero foreign keys.
I have to create it manually and clicking it a bit tedious.
The more features the application has, the more useful it will be for the user (as long as one function does not conflict with another).

**Comment by ask9** [comment]
Anyway, I appreciate that you maintain the application, answer the reports here and I accept any your choice.
