### ISSUE TITLE
Select and move more than one table in Relational Data Explorer

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#143]
I suggest to add feature to select and move more than one table over canvas.
User can press (and not release) Ctrl-key and left mouse click on captions of tables in Relational Data Explorer to selecte multiple tables.
After that he can relese Ctrl-key and drag & drop all the selected tables over a title of one of them.
It would make it easier to move and arrange multiple tables.
Here I have to move them one by one:

https://github.com/user-attachments/assets/c5c7ef93-fa9b-4b37-861a-97651077d956

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.6.2 build 240928
Windows 10
Postgres 16

3. The steps to reproduce this issue

**Comment by wise-coders** [comment]
We will create an internal ticket for this. I am not sure if is going to be implemented, as many of the toolbar options ( like insert record, delete, edit ) require maximal one frame to be selected. This may create confusion with this options.
