### ISSUE TITLE
Change color of virtual foreign keys

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#144]
I believe the chosen color of an arrow of a virtual foreign key on a diagram should be colored in such a way to distinguish easily between standard FK and virtual FK.
Now the color of virtual FK is barely distinguished due to chosen color (dark violet).
The color of standard FKs is dark gray.
For my point of view, it's nearly impossible to distinguish visually between them (based on local lighting and monitor brightness).

It maybe even better to do this color customizable (user can change the color in application settings).

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.6.2 build 240928
Windows 10
Postgres 16

3. The steps to reproduce this issue

![img1](https://github.com/user-attachments/assets/8969fcf9-7907-4aa1-af0b-ea78123c03e5)

**Comment by wise-coders** [comment]
This will be fixed in the next release. We will use a stronger color. 
You can also edit the custom.css file in the DbSchema/config/apperance and add:
.diagram, .diagram > .viewport {
    foreign-key-virtual: #96849c;
}
