### ISSUE TITLE
The search panel is not available and looks weird when the windows is half-divided

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#145]
The search panel is not available (in spite of available space on the toolbar) when the main window is half-divided (use hotkey Win + Left for Windows to half-divide the current window left/right).

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database

3. The steps to reproduce this issue
- press Win + Left
- open the seach panel in the upper right corner of the main window

https://github.com/user-attachments/assets/1a583a9a-9534-400b-9124-a6131b96ffba

**Comment by wise-coders** [comment]
Issue will be fixed in the next release.
