### ISSUE TITLE
Show name of the schema in a list of objects in the tree of a particular Layout

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#146]
I suggest to show name of the schema in a list of objects in the tree of a particular Layout.
If particular database has only one schema, it is ok to do not display schema name left of the table name.
But if there are more than one schemas, it would be nice to see the schemas here.
I would not like to have additional node with schema-name and all the tables in it (as it is done in Connection, Schemas, schema_name, tables). 
It would be enough to show schema in the same level along with table name, for example public.customer, sales.monthly_sales, etc.

For example, here I createad a schema and a table in it.
I dragged it onto layout.
In a list of all objects of a layout I expected to see: "sales.monthly_sales", but I see only "monthly_sales"

Use this code for reproduce it:

```
create schema sales;
create table sales.monthly_sales (
    id int
);

```

https://github.com/user-attachments/assets/bd69eb74-7cdc-4f82-ab22-119dc22691e9

1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.6.2 build 240928
Windows 10
Postgres 16

3. The steps to reproduce this issue

**Comment by ask9** [comment]
This is also only about node **Layout**, not Schemas

**Comment by wise-coders** [comment]
This will be fixed in the next beta update and next release.
https://dbschema.com/beta.php
