### ISSUE TITLE
Connecting to snowflake through SSO

### ISSUE THREAD

**Issue by daviewning** [wise-coders/dbschema#147]
1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database

3. The steps to reproduce this issue

Hi support team, have a question about the connect to snowflake using dbschema. Not sure whether dbschema support connecting to snowflake through SSO?

**Comment by wise-coders** [comment]
This should work by default. DbSchema is connecting using JDBC Driver provided by Snowflake, and the driver can do SSO.
In the DbSchema connection dialog you can choose 'Edit Manually' to choose a custom JDBC URL.
Please write a short reply in this thread, to know if you succeed. If not, please reopen it and we will assist.

**Comment by wise-coders** [comment]
Best regards,
 Dragos Pruteanu

> On Thursday, October 10, 2024 at 3:26:11 AM, DaveDevelop wrote:
>
> *
> Please check DbSchema Help / Output logs for errors.
>
> *
> Please include the DbSchema version, operating system and used database
>
> *
> The steps to reproduce this issue
>
> Hi support team, have a question about the connect to snowflake using dbschema. Not sure whether dbschema support connecting to snowflake through SSO?
> —
> Reply to this email directly, [1] view it on GitHub, or [2] unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID:

[1] https://github.com/wise-coders/dbschema/issues/147
