### ISSUE TITLE
Cannot find a way to add a description to Procedures and Functions

### ISSUE THREAD

**Issue by dredev89** [wise-coders/dbschema#15]
DbSchema version: 8.2.7 build 200130
Operating system: Windows 10 Pro (10.0.17134 build 17134)
Used database: SQL Server 2016 Developer Edition

The steps to reproduce this issue:

1) Create a Layout
2) Export the Layout to HTML, checking "Functions and Procedures"
3) Open the file and take a look at the section listing all the Procedures and Functions

A column with "Description" title exists, but I cannot find a way to add a description to a Procedure or a Function (in Documentation too).

![Description](https://user-images.githubusercontent.com/16489972/74859044-96bce780-5346-11ea-9386-81102592fbfb.PNG)

**Comment by kjones-lan** [comment]
While editing the procedure click <kbd>Edit</kbd>, <kbd>Comment</kbd>

![Edit-Comment](https://user-images.githubusercontent.com/60940068/74990652-743fd280-5409-11ea-8202-cf4722e6440c.png)

**Comment by dredev89** [comment]
> While editing the procedure click Edit, Comment
> 
> ![Edit-Comment](https://user-images.githubusercontent.com/60940068/74990652-743fd280-5409-11ea-8202-cf4722e6440c.png)

Thank you, this works.
The comment is not saved as an extended property, is it? 
So I guess that it is saved somehow in the project file, and running the reverse engineering procedure from a different dbschema project will not load the comment (table/column description would be instead).

**Comment by wise-coders** [comment]
This is correct, the comments are saved only in project file.
We can also add a statement to save them as extended property. This will work probably only for SqlServer. Do you think we should implement this ?

**Comment by kjones-lan** [comment]
> This is correct, the comments are saved only in project file.
> We can also add a statement to save them as extended property. This will work probably only for SqlServer. Do you think we should implement this ?

It's not a feature I'd want.
