### ISSUE TITLE
How to register license when running `DbSchema` headless

### ISSUE THREAD

**Issue by LuchoTurtle** [wise-coders/dbschema#151]
Hey there, again! 👋 

This issue follows the discussion from https://github.com/wise-coders/dbschema/issues/132, where I was able to run `DbSchema` in a `Docker` container headless in a GitHub Action workflow (you can check the code at https://github.com/dwyl/dbschema-demo).

Regarding using, I'm aware that there's a floating license that can be used (and it's [already documented](https://dbschema.com/documentation/dbschemacli.html#license-server)), but I'm wondering how I can use a regular license. This is in the context of generating an HTML5 page that renders unlimited tables (instead of the 12-table limit in the regular version of `DbSchema`).

According to https://github.com/wise-coders/dbschema/issues/132#issuecomment-2343931169:

> We will add more parameters to the DbSchemaCLI client register command.
> Tomorrow we will release a beta update with this features under: [dbschema.com/beta.php](https://dbschema.com/beta.php)

This was weeks ago, and I'm sure the feature has been implemented and is in production. However, I can't find any documentation on this. How can I register a license? Can I do it inside the Groovy script that I want to run?

**Comment by wise-coders** [comment]
We will add this public method into the next release:
com.wisecoders.dbs.cli.command.fls.RegisterCommand.register(File file)
where the file contains the license key.
The beta update will be released next Monday morning under
https://dbschema.com/beta.php

**Comment by LuchoTurtle** [comment]
Thanks!
You should add the method to your API Documentation (https://dbschema.com/javadoc/index.html) so it's easier for people to search for details.

**Comment by wise-coders** [comment]
You are right. The javadoc will be updated right today.
