### ISSUE TITLE
"Clone" button in "Database Connections" doesn't add a newly cloned connection to the list of connections until reopening this window

### ISSUE THREAD

**Issue by ask9** [wise-coders/dbschema#152]
1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database
DbSchema 9.6.3 build 241010
Windows 10
Postgres 16

3. The steps to reproduce this issue
- open database connections
- select any connection with mouse click
- click Clone button
- fill password and press Connect

expected: a new item in a list of connections appeared
actual: the newly created item in a list is not appeared. It appears on the next open of this window

**Comment by wise-coders** [comment]
The issue will be fixed in the next release.
