### ISSUE TITLE
Reverse Engineering Exasol DEFAULT NULL

### ISSUE THREAD

**Issue by ssteinhauser** [wise-coders/dbschema#154]
DbSchema does not recognize "DEFAULT NULL" values during reverse engineering of an Exasol database. When reverse engineering such columns, in DbSchema it seems, that the columns do not have a default value.

ALTER TABLE table_name ADD COLUMN column_name INTEGER DEFAULT NULL; -- default value is NULL
ALTER TABLE table_name ADD COLUMN column_name INTEGER; -- no default value is defined

1. Please check DbSchema Help / Output logs for errors.
No errors occur

3. Please include the DbSchema version, operating system and used database
DbSchema Version: 9.6.4
OS: Windows & Ubuntu Linux
Database: Exasol

4. The steps to reproduce this issue
Reverse engineer an Exasol database having a table with a column that has the default value NULL defined.

**Comment by wise-coders** [comment]
We will add support for this option. In case of Exasol we will save DEFAUL NULL to the column settings.
But may I ask, is it different from other databases? All have DEFAULT NULL by default ( if not value is specified, null will be used ).
A beta update will be available in about 2 days under https://dbschema.com/beta.php

**Comment by ssteinhauser** [comment]
Thank you!
It is actually the same behavior, so if a column is nullable, the default is DEFAULT NULL if no value is specified. However, it is represented differently in the catalog:

```sql
create or replace table test.test (id integer, id_default integer default null);
```

![image](https://github.com/user-attachments/assets/1537bd64-40de-4560-b835-fca0eddf51b8)
