### ISSUE TITLE
ClickHouse database support

### ISSUE THREAD

**Issue by Skandalik** [wise-coders/dbschema#157]
Is there any plan to support ClickHouse database single node + cluster mode? I saw that Cassandra and Exasol are supported and I was wondering if this is planned to be supported or maybe it's in the progress.

**Comment by wise-coders** [comment]
Please use the beta update from today: https://dbschema.com/beta.php
It has support for ClickHouse.
For connecting tot cluster, choose Edit Manually in the JDBC combo and jdbc:clickhouse://<host1>:<port>,<host2>:<port>,<host3>:<port>/<database>

Please write us about any other features. We are improving the support for Clickhouse.
