### ISSUE TITLE
Automatic relationship 

### ISSUE THREAD

**Issue by binalbhavsar1** [wise-coders/dbschema#17]
1. Please check DbSchema Help / Output logs for errors.
Hi, When we reverse engineer, does it create child and parent automatic relationship ? 
2. Please include the DbSchema version, operating system and used database

3. The steps to reproduce this issue

**Comment by kjones-lan** [comment]
No, it creates "virtual" relationships that do not modify the schema

**Comment by wise-coders** [comment]
DbSchema does reverse engineer the foreign keys from the database, if they exists there.
If not you can : 
1. create virtual foreign keys. Is right, they won't be created in the database but only in the project file.
2. use the automation scripts ( check the Help ) to automate creating (virtual) foreign keys in the local project.
