### ISSUE TITLE
Fullscreen breaks on large monitor

### ISSUE THREAD

**Issue by DaveDevelop** [wise-coders/dbschema#2]
1. Please check DbSchema Help / Output logs for errors.
I don't see anything in the log viewer, but the error does make it into the log file
[logs.zip](https://github.com/dbschema-designer/dbschema-issues/files/4157282/logs.zip)

2. Please include the DbSchema version, operating system and used database
3 monitor, the larges is 2560x1600
V 8.2.7 build 200204 (but its been this way for many version now)
Windows 10
Postgres

3. The steps to reproduce this issue
Open DBSchema: It auto opens my Project: Maximise Window:
It appears to be a painting error,  the outer edges are black, and I cannot use the mouse to select anything
Even if I restore the Window Mode, its still un responsive

This does not happen on my smaller monitors (1920x1080)

**Comment by wise-coders** [comment]
Could you please edit DbSchema.vmoptions and add this option ( just check how much graphic memory you have ):

-Dprism.maxvram=200M

The file can be found in the same folder as DbSchema.exe

I think the issue is related to graphic memory, which is probably not enough for your case.

**Comment by DaveDevelop** [comment]
Thanks,
It was already set to 2G (not sure when I did that)
so at 200M it wouldn't even open the file, but at 3G is working
I can see is now using around 2.4
Maybe its related to all my open layout see: #3
