### ISSUE TITLE
After update to 8.2.8 insisting on invalid key cannot use product anymore

### ISSUE THREAD

**Issue by kemin711** [wise-coders/dbschema#20]
1. same problem happened to me before.  Took a long time to resolve.  As a result I could not use the product for several weeks. 
Trial has expired

2. DbSchema just updated to 8.2.8, Mac OS 10.14.6

3. After automatic update and install, got stuck in this state

**Comment by wise-coders** [comment]
Reason for this can be the registration name which is not correct or the license ( if is older then 1 year ). DbSchema include free updates to new released versions for 1 year. After that a renewal license is required.
Please open a ticket using the 'sales' option on the DbSchema support website page, and give more details ( the purchase email or order number ). Then I can check this issue.

**Comment by kemin711** [comment]
Thanks.It has no problem until I did automatic update.  The key was supplied when I renewed my key on May 11th 2019.  Still got some time before expiring.  I will open a ticket as you suggested.  
It is clearly a bug either in your app or in your database.  This is not the first time having such problems.It looks recurring bug.
Kemin Zhou 858 771-3269 

    On Tuesday, March 3, 2020, 09:55:39 PM PST, Wise Coders <notifications@github.com> wrote:  
 
 
Closed #20.
