### ISSUE TITLE
Filtering options on schema selection dialog

### ISSUE THREAD

**Issue by lucacestola** [wise-coders/dbschema#25]
Version 8.2.9 / Windows / Sql Server

We have a Sql Server instance for development and we use dbschema against it. Although it is correct that the current selection dialog shows all the schema reachable by the connected user, it would be useful to have more filter options.

In our case, there are several databases that correspond to different versions of our products and therefore they contain a set of schema that repeats itself for each database (each with thousands of database objects). Filtering by schema name, doesn't avoid to get a long list and pay attention to the right database version. In addition, the name of one of the schema, corresponds to the prefix of the database name. These conditions often make it difficult to reduce number of elements.

![image](https://user-images.githubusercontent.com/3340280/78688640-c1163480-78f5-11ea-8d3e-0db92ef11219.png)

It would be convenient to have more filter options. Being able to filter by database first, would help a lot in restricting the number of schema.

**Comment by wise-coders** [comment]
Hello,
The current DbSchema version from website has a fix for this. The version number is still 8.2.9 but the build number is higher. We support regexp in the filter field, which probably will help you.

![image](https://user-images.githubusercontent.com/60284259/79096340-29816d80-7d5d-11ea-8723-6b69338d2626.png)
