### ISSUE TITLE
Hotkey not work if active not English keyboard layout 

### ISSUE THREAD

**Issue by blacksnake-rus** [wise-coders/dbschema#27]
Hotkey (Ctrl+C, Ctrl+Z, Ctrl+V, Ctrl+A) not work if active not English keyboard layout (Russian in my case)

DbSchema version 8.2.7 build 200205, Windows 10, PostgreSQL

**Comment by wise-coders** [comment]
May I ask which operating system do you use ( Mac, Windows, linux )? Also, is the problem in SQL editor ?

**Comment by blacksnake-rus** [comment]
> May I ask which operating system do you use ( Mac, Windows, linux )? Also, is the problem in SQL editor ?
Windows 10
Yes, problem in SQL editor.

**Comment by wise-coders** [comment]
Thank you for reporting this issue. Now is fixed. Please download the current DbSchema version from website, it is still version 8.2.9 but a higher build number.
