### ISSUE TITLE
Schema based view sync is broken

### ISSUE THREAD

**Issue by Qwerios** [wise-coders/dbschema#28]
DBSchema: 8.2.9
MacOS 10.15.3
Java 1.8.0_152
Database: Postgresql 9.6

I work with various schemas inside my database each with their own tables and views.
My view changes are synced from my test database into DBSchema.
The view definition appears to replace the schema name with a `${schema}` placeholder.
When I sync to my production database the change generated is:

```sql
DROP VIEW my_schema_name.my_view;

SELECT myschema.my_table ....
```

Note the lack of the `CREATE VIEW ...` syntax. This causes an error

Steps to reproduce issue:

1) Change a view in database on connection A
2) Sync changes to model
3) Detect changes with connection B
4) Sync changes/generate script for connection B

Step 4 will contain invalid sql. This appears to be happening since the schema placeholder variables started appearing.

I've tried reverse engineering a fresh model file but this still has the same issue. My database projects have anywhere between 3 to 11 schemas.

**Comment by Qwerios** [comment]
I've updated from build 200330 to 200422.

I'm now seeing more `${schema}` markers show up and the CREATE VIEW syntax is now part of the view definition in the editor which is new. 

However the DROP statements preceding the calls do not contain a schema. If you have the same view name in the public schema this has a chance of dropping a completely different view.

**Comment by wise-coders** [comment]
Thank you for reporting this issue. May I ask to install the current DbSchema version from website ? Is still version 8.2.9 but is a higher build number. 
I have tested views with Postgres 9.4 and they are working fine for me.
Please let me know if the issue is fixed for you as well.

Is true, we added ${schema} and ${name} in the definition. We did this as for some databases there could be multiple options to create a view.

![image](https://user-images.githubusercontent.com/60284259/80407395-d9122000-88c5-11ea-940f-c56e935be9d6.png)

**Comment by wise-coders** [comment]
You are right about dropping the view. Please replace ${name} with ${identifer} in the Project / Settings / Rdbms Syntax / Drop view.  We will add a fix also in the upcoming version.

![image](https://user-images.githubusercontent.com/60284259/80407879-9bfa5d80-88c6-11ea-923d-c25270c7c7e1.png)

**Comment by Qwerios** [comment]
Updated to 200427. Seems to have fixed most issues except the DROP syntax. I changed the syntax as you suggested and that seems to work.

I also had to apply the same change to:

* VIEW comment
* MATERIALIZED VIEW drop
* MATERIALIZED VIEW comment

What is going to happen with these modifications when the next version/update of dbschema comes along?

**Comment by wise-coders** [comment]
Thank you for reply. We will implement this changes in the next version as well. The changes you made are saved in user home .DbSchema/config/rdbms/PostgreSQL/syntax.properties.
Should be only the modified records. 
When you get the new version you can do 'Reset default' in the Project / Settings dialog.
