### ISSUE TITLE
Synchronise new schema

### ISSUE THREAD

**Issue by Qwerios** [wise-coders/dbschema#29]
DBSchema: 8.2.9
MacOS 10.15.3
Java 1.8.0_152
Database: Postgresql 9.6

When creating a new schema with DBSchema in offline mode there is no way to sync the new schema to a database.

Steps to reproduce:

1) Set DBSchema to offline
2) Create new schema (optionally add tables or views)
3) Activate a connection
4) Synchronise changes

In step 4 there is no way to sync schemas unknown on the database side. I would have do a `CREATE SCHEMA my_schema` manually on the target database before an option is given. A detection of missing schemas would be very welcome.

**Comment by wise-coders** [comment]
Please install the current DbSchema version from website, from today. Is still version 8.2.9 but a higher build number. We had some fixes under this build.
I have tested and for me it works fine: 
![image](https://user-images.githubusercontent.com/60284259/80142104-e9b35500-85aa-11ea-9078-1d4f3769c436.png)

Please let me know if this version works fine for you.

**Comment by Qwerios** [comment]
Updated from build 200330 to 200422

Okay it works if you use the `Schema -> Create or upgrade schema` option.
I usually use the `Schema -> Refresh/Compare local schemas with database` option which does not provide the options.

I sometimes have view changes that are created on the database itself by other developers so we rely on sync a lot. This is a working solution for me.
