### ISSUE TITLE
Export All Layouts

### ISSUE THREAD

**Issue by DaveDevelop** [wise-coders/dbschema#3]
I have 300 tables, and 35 layouts
I need to be able to export to HTML to share with others.
Currently this requires keeping all these layouts open, even though I only regularly use 5-10 of them.

It would be ideal to have an option to export All Layouts instead of having to use All Open Layouts

**Comment by wise-coders** [comment]
We will consider also adding the option you suggested.

A quick solution for this is to use the 'Load project files from folder and generate HTML documentation' script from [automation-api script](https://dbschema.com/documentation/automation-api.html).
This allows to generate documentation by using Groovy from SQL Editor for all project files from a folder.

**Comment by DaveDevelop** [comment]
That works for me, Thanks!
My only feedback would be that it would be nice to get feedback when the script errors (ie line number)
there doesn't seam to be anything in the log
