### ISSUE TITLE
Drag and drop from a field does not starts foreign key creation anymore

### ISSUE THREAD

**Issue by lucacestola** [wise-coders/dbschema#31]
Version: DbSchema 8.2.11 build 200624
OS: Windows 10
Java version: OpenJRE 14.0.1

In previous versions you could create a new FK by drag and drop from source field to target field.

By this release, dragging from a field always starts table movement

![image](https://user-images.githubusercontent.com/3340280/85702458-b7bf8b80-b6de-11ea-97a5-59b1f3847bed.png)

Also, after dragging by clicking on a field, immediately opening the context menu on the same field leads to a different menu layout:

![image](https://user-images.githubusercontent.com/3340280/85703233-74195180-b6df-11ea-98a8-d34f3d27179a.png)

while clicking on a field without the previous described drag action shows the expected contextual menu:

![image](https://user-images.githubusercontent.com/3340280/85703375-96ab6a80-b6df-11ea-9447-672397fbea7c.png)

**Comment by dprutean** [comment]
Hello,
Thank you for reporting this issue. I tried to reproduce this under the same version, but I could not. For me from the screnshot it looks like the table header and the column are selected both in the same time. Which means the drag and drop sees also the table as selected. Could you please check this ? 
I tested this as well ( drag a column when the table header is already selected )  and for me the table header selection is away when clicking the column.

**Comment by lucacestola** [comment]
You are right. I had that behavior since I restarted dbschema and now it all works as expected. Few days have passed since the issue was opened but it's hard to remember what I did just before. Maybe a selective synchronization, a layout re-arrangement and a table creation. I think you can just close the issue because the problem is not replicable.
