### ISSUE TITLE
SQL Editor don't respect selected connection

### ISSUE THREAD

**Issue by danito8905** [wise-coders/dbschema#32]
**DbSchema version: 8.2.12 build 200703
Operating system: Kubuntu 20.04
Database: MySQL Server 8.0.19**

1- select a database connection
2- open a new sql editor and run a query, ie `select count(*) from some_table`
3- select a diferent connection in the same server but different database (different quantity of rows for better test)
4- in the same opened sql editor, re run the same query. 

It will return the result running the query in the previous selected connection.

If you open a new sql editor and run the query, then will run in the current connection as expected.

**Expected**:  run a query in a opened sql editor should respect the current selected connection, if not it is dangerous.

**Comment by wise-coders** [comment]
Thank you for writing about this issue.
This will be fixed in version 8.3.0, which will be released soon.

**Comment by danito8905** [comment]
Hi, I have updated to 8.3.0 version and the issue is still present.

**Comment by danito8905** [comment]
also in version 8.3.1 as I could see.

**Comment by wise-coders** [comment]
Issue is fixed in the current release.
