### ISSUE TITLE
Connector API enhancement

### ISSUE THREAD

**Issue by lucacestola** [wise-coders/dbschema#33]
DbSchema 8.3.1 build 200908
SO: Windows 10 (x64)

you recently added the importSchemes method to the Connector class and this simplifies the automation script, however it would be useful to do partial imports by specifying list of object (among tables, views, procedures, etc.)

This should speed up imports with large amount of objects and avoid unnecessary waiting. I hope there is room for this improvement

**Comment by dprutean** [comment]
In the next minor upgrade, we will add one parameter selectionCallback to this method.
This receives a TreeSelection object, where you can choose the schemes, tables, etc to import or not.
public List<Schema> importSchemes(Callback<TreeSelection,Void> selectionCallback, String... catalogDotSchemaName ) throws Exception.

For convenience, we will keep also a method 
public List<Schema> importSchemes(String... catalogDotSchemaName ) throws Exception
without this parameter.

A beta will be available after 2 days from now [here](https://dbschema.com/beta.php)

**Comment by wise-coders** [comment]
Close issue
