### ISSUE TITLE
SSH Tunnel to AWS RDS/Aurora Does not work

### ISSUE THREAD

**Issue by darkredz** [wise-coders/dbschema#34]
DBSchema is not able to connect to Mysql database when using a connection with SSH Tunnel to AWS RDS/Aurora through a jump server in EC2 with port 3306 allowed.

When connect it will throw the following error
com.jcraft.jsch.JSchException: PortForwardingL: local port 127.0.0.1:3306 cannot be bound.
  at com.jcraft.jsch.PortWatcher.<init>(PortWatcher.java:158)
  at com.jcraft.jsch.PortWatcher.addPort(PortWatcher.java:110)
  at com.jcraft.jsch.Session.setPortForwardingL(Session.java:1847)
  at com.jcraft.jsch.Session.setPortForwardingL(Session.java:1828)
  at com.jcraft.jsch.Session.setPortForwardingL(Session.java:1809)
  at com.jcraft.jsch.Session.setPortForwardingL(Session.java:1792)
  at com.wisecoders.dbs.schema.Connector.d(Connector.java:912)
  at com.wisecoders.dbs.schema.Connector.setupSSHTunnel(Connector.java:784)
  at com.wisecoders.dbs.rdbms.connect.model.FxPingTask.a(FxPingTask.java:32)
  at com.wisecoders.dbs.rdbms.connect.model.FxPingTask.call(FxPingTask.java:13)
  ...

2. Please include the DbSchema version, operating system and used database
v8.3.2 Mac OS Catalina, MySQL 5.6.1

3. The steps to reproduce this issue
- Setup a SSH Tunnel in the connection pointing to the EC2 instance within the same VPC as RDS, eg. ec2-11-111-111.us-east-2.compute.amazonaws.com and use a private key file
- Set JDBC URL to Remote computer and put in the RDS/Aurora hostname eg. dbname.cluster-xxxxxx.us-east-2.rds.amazonaws.com

**Comment by Mano7799** [comment]
I am kinda facing the same issue. I am trying to connect AWS Redshift database using SSH. But it wont connect. It throws "connection time out". Any work around to resolve this?

**Comment by wise-coders** [comment]
We didn't check this recently, but could you please first check if is any setting in AWS for enabling remote connectivity?
Please stop any local MySql instance (running on your computer), this can lead to port conflicts.
Please let me know if any of this does help, and if not I will create a ticket for the team.

**Comment by wise-coders** [comment]
Did you got connected? Please let me know, I would close the issue.

**Comment by darkredz** [comment]
yes it works

**Comment by Mano7799** [comment]
No, For me it didn't get connected. It says "Connection Time out".

**Comment by wise-coders** [comment]
For Mano: please contact us using the Help / Report a bug dialog from DbSchema. Let's set up a web meeting and check this together. Is this ok for you?

**Comment by Mano7799** [comment]
We can!
But wanted to clarify one thing prior, Is it mandatory to make the Redshift Database public access enabled? Becoz, Our Database isn't.

**Comment by wise-coders** [comment]
I think yes, you should make it public, but you can do this only for a certain client host or network.
Could you please also ask AWS support by creating a ticket? They know the best about this.
The technical support should be free for you. We have only a limited AWS plan. 

Please write us as well about what answer you got.
