### ISSUE TITLE
Presale question - How do I produce a report showing all columns of all tables with a description? (SQLServer)

### ISSUE THREAD

**Issue by gcontrabass** [wise-coders/dbschema#35]
This is a presale question:

I need to be able to produce ERDs and data dictionaries for relatively simple SQL Server  and Azure SQL databases.
I am happy with the ERDs but don't know how to produce something that will show all column metatdata by table for an entire schema.
Does dbschema automate that for me?

Thank you.

**Comment by dprutean** [comment]
Please check first the Layout / Export HTML5 documentation. This includes the diagram vector image.
If you need a custom output format, you can use Groovy scripts (Groovy is pure Java) to generate them. The scripts have direct access to DbSchema API and all internal classes. Have a look at the automation page in DbSchema website Documentation. If needed, we can help to write a script for this.
