### ISSUE TITLE
Groovy: unable to resolve class Generator in Data Generator

### ISSUE THREAD

**Issue by baklarzej** [wise-coders/dbschema#37]
Hello, I have a following error in Data Generator:
![dbSchema Generator](https://user-images.githubusercontent.com/28765790/105466675-e1e92400-5c94-11eb-9c3d-5177c384adbe.png)
Groovy, when launched from "SQL Editor" on the other hand, works fine.

1. Please check DbSchema Help / Output logs for errors.

The message coming in Data Generator is:
`startup failed:
Script1.groovy: -1 unable to resolve class Generator
@ line -1, column -1.
1 error`

2. Please include the DbSchema version, operating system and used database
DbSchema version 8.3.5 Build 210121
Windows 10 Pro version 1909
Oracle 19 Database

3. The steps to reproduce this issue
- Go to Data Generator
- Select a table and then a column 
- Click "Edit generator"
- In the "Pattern" field, provide a condition starting with "groovy: "
- Error will be thrown in samples

**Comment by wise-coders** [comment]
Thank you for reporting this issue. Now is fixed, available next day from now under this link: https://dbschema.com/beta.php
