### ISSUE TITLE
Can't export HTML Doku

### ISSUE THREAD

**Issue by Hankern1996** [wise-coders/dbschema#38]
Under Layouts is no such "Export HTML Dokumentation"
![Bildschirmfoto 2021-02-12 um 09 08 53](https://user-images.githubusercontent.com/33423645/107743840-f2c80b00-6d11-11eb-901f-7faf33bebc03.png)

**Comment by Hankern1996** [comment]
MacOS

**Comment by dprutean** [comment]
The Export HTML5 documentation is available in the DbSchema Pro version. You can request an evaluation key and should be there. May I ask where you saw the message about this? Maybe we wrote somewhere confusing, we can fix.

**Comment by wise-coders** [comment]
Close issue
