### ISSUE TITLE
dbShell with access driver unable to open file

### ISSUE THREAD

**Issue by joaocc** [wise-coders/dbschema#40]
I am trying to open a connection to a MSAccess file using dbShell.
Things work well with dbSchema on same machine.
How can I get some kind of logging / debug info, that can tell me what is being searched as file path?
Thx

```
/Applications/DbShell/dbshell

Not Connected > connection DB.v1.MDBX Access "jdbc:ucanaccess:///Users/uuu/MYCORP rootdir/@SOMEDIR/otherdir/MYDBname.accdb"
OK

Not Connected > connect DB.v1.MDBX
UCAExc:::5.0.1 given file does not exist: <file>

connection BB Access jdbc:ucanaccess:///tmp/a.accdb
Ok

Not Connected > connect BB
UCAExc:::5.0.1 given file does not exist: <file>
```

**Comment by wise-coders** [comment]
The <file> is a tag in the JDBC URL. You have to specify a value for the file, like file=/path/... in the connection command.
