### ISSUE TITLE
Layout keeps snapping everything to the left

### ISSUE THREAD

**Issue by zork2112** [wise-coders/dbschema#45]
I'm working on a layout for a few tables and want to have them show in the center of my screen.  I can move one table to the center, but if I align one below it (just two tables - this is a start up), it snaps it back to the left of the screen.

**Comment by wise-coders** [comment]
I see. Right now we are working like this, the tables are aligned to left. I will create an internal ticket for us, which will be implemented later. Right now we are introducing the logical design in DbSchema.

Best regards,
 Dragos Pruteanu

PS. Any feedback about DbSchema or database-specific issues is welcome.

**Comment by wise-coders** [comment]
Will stay like this. The feature works fine for larger layouts, small layouts will be centered.
