### ISSUE TITLE
DATAGENERATOR pb with load_values_from_pk

### ISSUE THREAD

**Issue by sebmay** [wise-coders/dbschema#47]
Hello,

On a table, the pk is named 'id'.
There is a self-reference bigint, named parent_id.
That is used to create a tree of objects. The root objects have nilled parent_id.
I have many trees of objects in my app.
load_values_from_pk generate the literal string 'load_values_from_pk'

BTW, the key definition is :

for the id key column :
-- Constraint: orga_pkey
-- ALTER TABLE public.orga DROP CONSTRAINT orga_pkey;
ALTER TABLE public.orga    ADD CONSTRAINT orga_pkey PRIMARY KEY (id);

for the parent_id column :
-- Constraint: orga_parent_id_fkey
-- ALTER TABLE public.orga DROP CONSTRAINT orga_parent_id_fkey;
ALTER TABLE public.orga
    ADD CONSTRAINT orga_parent_id_fkey FOREIGN KEY (parent_id)
    REFERENCES public.orga (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

Then i suspected that load_values_from_pk does not work when the reference is in the same table, if you generate the records in one transaction.

Then i tried to use groovy: using the example with the cost value. I wrote :

groovy: if (id > 0) return id-1; else return NULL;

I get the error :
No such property: id for class:Script1

I think your example in the help file is wrong.
Can you help, please ?

Cordially,
Sebastien

**Comment by wise-coders** [comment]
This issue will be fixed in the next minor update. Please also use this pattern (the null keyword is case sensitive) : 
groovy: if (id > 0) return id-1; else return null;

**Comment by wise-coders** [comment]
Best regards,
 Dragos Pruteanu

PS. Any feedback about DbSchema or database-specific issues is welcome.

**Comment by sebmay** [comment]
Thanks, i'll get on that point now...
