### ISSUE TITLE
Strings from list or file

### ISSUE THREAD

**Issue by sebmay** [wise-coders/dbschema#48]
Hello,

This point is not a BUG, but a kind of wish.

Given a list of string. Let say 10 strings. In literal (...|...|..) or list of strings in file.

Given a number of row expected LESS OR EQUAL than 10 (in this example).

I would like to have no duplicates !

More generally, given a "unique" constraint on a field, if the previous case is not fullfiled, i.e. 10 strings in the list, but i want 300 rows, find a way (you impose a way) to generate uniques items by adding a suffix. Like _<number>.

I will try to manage with groovy for now...... Maybe use a sequence as an index in an array of strings. But that's heavy !
Cordially,
Sebastien

**Comment by wise-coders** [comment]
This can be done with Groovy. Just add suffix in a loop, as long as the insert fails ( duplicate value ).
