### ISSUE TITLE
Bug: DbSchema MSSQL Can Not Create Composite/Combined Foreign Key with the UI

### ISSUE THREAD

**Issue by VictorioBerra** [wise-coders/dbschema#50]
DbSchema 8.4.3
Windows 10
SQL Server 2008

IE:

```sql
CONSTRAINT FK_MembershipPeriod_BandMember FOREIGN KEY (MusicianID, BandId) REFERENCES BandMember(MusicianID, BandId)
```

How can I do this in the UI?

**Comment by VictorioBerra** [comment]
Closing as I misunderstood something.

**Comment by VictorioBerra** [comment]
Okay im gonna re-open this as a bug.

I have a composite primary key on my table.

I create a composite foreign key in dbschema.

dbschema generates this:

```sql
ALTER TABLE DEStandards.DepartmentComputerFunctionalAreaLine ADD CONSTRAINT Fk_DepartmentComputerFunctionalAreaLine_Department FOREIGN KEY ( DepartmentId, CampusId ) REFERENCES DEStandards.Department( Id, CampusId ) ON DELETE NO ACTION ON UPDATE NO ACTION
```

this fails with:

```
There are no primary or candidate keys in the referenced table 'DEStandards.Department' that match the referencing column list in the foreign key 'Fk_DepartmentComputerFunctionalAreaLine_Department'.
```

It should have generated this:

```sql
ALTER TABLE DEStandards.DepartmentComputerFunctionalAreaLine ADD CONSTRAINT Fk_DepartmentComputerFunctionalAreaLine_Department FOREIGN KEY ( DepartmentId, CampusId ) REFERENCES DEStandards.Department( Id, CampusId ) ON DELETE NO ACTION ON UPDATE NO ACTION
```

![image](https://user-images.githubusercontent.com/2934507/127257787-4334e662-0568-4d92-acab-0ff852ba451a.png)

![image](https://user-images.githubusercontent.com/2934507/127257821-80453ed8-ce9b-487b-bf93-b8d9ade3e25e.png)

This should create a composite foreign key. The dialog does not seem to allow this, but the primary key dialog seems to allow it.

**Comment by wise-coders** [comment]
There is something wrong here. In your post, the first and 3-rd commands are the same. I don't see where the problem is.

I tested this with 2 tables in Postgres:

I added the foreign key  and the statement was correct:

Best regards,
 Dragos Pruteanu

**Comment by VictorioBerra** [comment]
@wise-coders I am not sure what I was doing wrong. I cleared my DB connection and went offline, I deleted all foreign keys, and I created new ones pointing to my composite key and everything seems to work now. The UI shows a single line between my tables with the keys comma delimited.

**Comment by wise-coders** [comment]
Please reopen this ticket if the issue happens again.
