### ISSUE TITLE
Postgresql role?

### ISSUE THREAD

**Issue by GKTheOne** [wise-coders/dbschema#51]
How can I `SET ROLE` before changes are pushed to the database?

**Comment by wise-coders** [comment]
I think the Model /Settings / DbSettings / Initialization Script 
may do the job. 
![image](https://user-images.githubusercontent.com/60284259/131488507-e732cff2-ecce-4748-8107-5865beba0e75.png)

**Comment by GKTheOne** [comment]
Thank you. That suits my use case beautifully. Apologies for missing it.
I'm happy to close this issue right now 👍 

Just thinking out loud now, but how hard/would it be possible to add initial sql/script to the connection?
I'm thinking of a use case where someone might need different initialization per database instance.
The initialization script referred to above is tied to the model, and I can tie before/after scripts to individual objects/schemas, but (ie) what if someone has different connection roles between dev/test/production instances?
Valid use case or Overthinking?
I'm just throwing this out for thought/discussion. I don't actually need this at the moment, and will create a new issue if I did in the future.

**Comment by wise-coders** [comment]
This would be possible. But we should have a consistent reason to implement it. Most of the users are using a single database, so the actual implementation is fine. But as you said, if needed we can implement it.
