### ISSUE TITLE
Zoom In / Out Controls for HTML5 Documentation

### ISSUE THREAD

**Issue by dshastry** [wise-coders/dbschema#52]
DBSchema HTML5 documentation can get fairly large and when working with a keyboard/mouse its hard to navigate around the diagram. 

Would it be possible to add the "perspective" feature similar to the desktop app or simple zoom in/out controls to the generated docs? We can do this manually by editing the HTML but I would prefer not to as each new generation overwrites the file.

Thank you!

**Comment by wise-coders** [comment]
This will be implemented in the next version. A beta release will be available in 2 days under https://dbschema.com/beta.php
The beta version will still be 8.4.4, the build number will increase. The zoom will work with CTRL+Mouse Wheel. Panning will be also available.

**Comment by dshastry** [comment]
Thank you for the fast turn around! Very much appreciated.
