### ISSUE TITLE
Postgres partial unique index

### ISSUE THREAD

**Issue by michaelstack** [wise-coders/dbschema#56]
Postgres supports partial unique indexes.

The relevant docs are at https://www.postgresql.org/docs/current/indexes-partial.html

I am working on a postgres database managed by dbschema. I want to create a partial unique index. It looks like these are not supported in the UI.

If this is supported in the UI could you please tell me where I should be looking in the docs? If it is not supported, is there a workaround?

**Comment by wise-coders** [comment]
In the Index dialog, use the Options combo to add the where clause:
![image](https://user-images.githubusercontent.com/60284259/144460533-5209faff-061b-4b63-a032-69a257f142cf.png)

I have checked, and this indexes are also reversed engineer correctly from the database: 

![image](https://user-images.githubusercontent.com/60284259/144460685-4b81f8e1-6a67-481c-8d79-fb458658a558.png)

**Comment by michaelstack** [comment]
That's awesome!

Thanks for the quick response.
