### ISSUE TITLE
Option to exclude collation from diagrams/documentation?

### ISSUE THREAD

**Issue by davidfrankson** [wise-coders/dbschema#57]
Is there a way to hide collation from diagram and documentation data type?

**Comment by wise-coders** [comment]
Could you please explain the reason to exclude it?
You can drop it using a Groovy script ( see Help  / Automation Scripts ), but I don't see the reason to have it in some situations and not have it in others. This may be inconsistent...

**Comment by davidfrankson** [comment]
I'm not sure on the conditions on when it is displayed in the diagrams but all collations are displayed for all fields.  We are in the process of trying to move the default collation to UTF-8, so maybe they appear when the column doesn't match the instance default?  All existing diagrams need to be resized and repositioned to have space for the big collation strings(which are truncated anyway) and the tables of fields are much bigger with lots of redundant information.  Overall we use diagrams to communicate core relationships with field types and the collations make everything extra busy with less valuable information.

**Comment by davidfrankson** [comment]
OK, so I figured out the pattern that makes it appear, not appear...

If the column matches the server/instance collation, then it does not display in the diagrams when you turn on "Show Column Data Type".  If the collation does not match the server/instance collation then it displays in the diagram.  My problem is I built dozens of diagrams and positioned everything based off collation not being displayed in the column data, then my instance changed collation to UTF-8 even though the database and columns remain at the old collation, and now none of my diagrams fit right as the large collation strings cause everything to be resized.  

I'd prefer more explicit control over showing/hiding collation in the diagrams.

**Comment by wise-coders** [comment]
DbSchema reverse engineer the tables using SHOW CREATE TABLE... in MySql. Everything which is returned is used to create the Table object. Probably MySql does not return the collation if is the same as the database default value.
To remove it from DbSchema, look also at the Schema / Synchronization Settings dialog, and Help / Automation Scripts. 
The scripts can use Java Groovy (which is pure Java ) to do different operations. You can simply remove the table and column options related to collations using regular expressions. If you want to keep some settings, but avoid showing them somewhere, please add more screenshots, to check if we can improve something.
