### ISSUE TITLE
Suggestion: Allow custom menus to run groovy script on open model

### ISSUE THREAD

**Issue by brettshearer** [wise-coders/dbschema#59]
Not sure if I have just missed in the documentation, but is there the ability to add menus that can be run from within DBschema (or to run a groovy script immediately before generating the database creation script)?

**Comment by wise-coders** [comment]
I am not sure what kind of operation do you need to add. Is it something you need to add in the generated schema, or what should the script do?
For something to add to the script, please check the Schema / Synchronization Settings. There is a Pre and Post script.
There are also Sync Filters - look the Help / Automation Scripts.
