### ISSUE TITLE
Question: Can the dbschema app functionality can be accessed via  cli

### ISSUE THREAD

**Issue by ermaugustinas** [wise-coders/dbschema#61]
Hi, thank you very much for a great product! We are looking to automate our database versioning, which looking at the app can mostly be done manually via the application.

Is it possible to replicate the same within an environment such as Azure Pipelines, where no UI is available.

The workflow in example:
* Generate model from an SQL file.
* Compare that model against an existing database
* Generate an SQL script to match the two databases.

**Comment by wise-coders** [comment]
Please check the Help / Automation Scripts dialog. The steps you included here are scripted in there. If more assistance is needed, please write back and I will help.

**Comment by ermaugustinas** [comment]
Hi, I tried downloading the linux distribution from https://dbschema.com/download/DbSchema_unix_8_5_2.tar.gz.
and I created a simple script: `out.println("Hello worlds")`, but after running: `./DbSchema -x ./sync.groovy` there is no output

**Comment by wise-coders** [comment]
You are right, this is an issue. We will fix this in the next minor release.

**Comment by ermaugustinas** [comment]
Thanks so much for your responses! Do you have an idea of how long it might take for the next release? A month, two weeks, etc.

**Comment by ermaugustinas** [comment]
Hello, I'd like to test the beta version if it's ready :)

**Comment by wise-coders** [comment]
Today the beta is ready: 
https://dbschema.com/beta.php
The version number is the same, the build number is higher.

**Comment by ermaugustinas** [comment]
The functionality is now working, I'm closing the issue
