### ISSUE TITLE
Reflect existing table/column comments as descriptions

### ISSUE THREAD

**Issue by dhirschfeld** [wise-coders/dbschema#62]
In my databases the tables and columns are documented with comments.

I'd like to provide a dbschema layout diagram as part of my documentation but if the generated HTML doesn't reflect the documentation in the database it's a bit of a non-starter for me :(

**Comment by dhirschfeld** [comment]
***xref:*** https://www.red-gate.com/simple-talk/databases/sql-server/tools-sql-server/towards-the-self-documenting-sql-server-database/

**Comment by wise-coders** [comment]
We do save the comments and also reverse engineer from the database, as the extended property 'MS_Description'. You can configure this property in Model/Settings/SqlSyntax and ReverseEngineer/Other.
Please let me know if this works fine for you.

**Comment by dhirschfeld** [comment]
Yep, sorry. The issue was with the library I'm using to generate the schema which doesn't support comments on SQL Server.

I'll close this since the problem isn't with `dbschema`...
