### ISSUE TITLE
Support for security policies

### ISSUE THREAD

**Issue by ermaugustinas** [wise-coders/dbschema#64]
Hi are there any plans (or already exists) to add support for security policies of SQL server?
When using automation scripts for comparing two databases, they are not added as part of migration.

**Comment by wise-coders** [comment]
Is this about CREATE SECURITY POLICY?
Can you please check the Schema / Synchronization Settings/ Pre and Post Synchronization Scripts? Does this help?

**Comment by ermaugustinas** [comment]
> CREATE SECURITY POLICY
Yes that's the one.

> Can you please check the Schema / Synchronization Settings/ Pre and Post Synchronization Scripts? Does this help?
Do you mean that it should work and I'm just missing an option to select, or that I should write a custom handler within Pre/Post Synchronization scripts

**Comment by wise-coders** [comment]
Right now they are not included in the reverse engineer. We plan to add them in the next releases. The Pre/Post Sync Scripts are a workaround.

**Comment by ermaugustinas** [comment]
Thanks for the clarification
