### ISSUE TITLE
Error trying to open .dbs on Linux

### ISSUE THREAD

**Issue by hsequeda** [wise-coders/dbschema#65]
I get this error when I try to open a .dbs file.
OS: Ubuntu
Version: 8.5.2 build 220308

It works ok on MacOS 
![2022-04-05_10-35](https://user-images.githubusercontent.com/46435362/161778423-2a76b9c9-2ab3-428b-94a4-116ea5eae9d6.png)

**Comment by wise-coders** [comment]
Please send a copy of the model file to support@dbschema.com (if the file is not private).
We need it in order to find the issue.
