### ISSUE TITLE
Relationships do not appear in MariaDb if database has a `-` in the name

### ISSUE THREAD

**Issue by rippo** [wise-coders/dbschema#67]
Log error message is

`You have an error in your SQL syntax; 
  check the manual that corresponds to your MariaDB server version for the right syntax 
  to use near '-gateway' at line 1`

`09:00:48 ==== 2022-04-25 09:00:48 DbSchema #220412 Windows 10 10.0 Java AdoptOpenJDK 15.0.2 ==`

The steps to reproduce this issue. create a database using `MariaDb` and put a `dash` in the database name. Create 2 tables with a simple `one-to-many` join

![2022-04-25_09-01-09](https://user-images.githubusercontent.com/772549/165046013-0580b1c2-997d-4f77-a841-e6655b60d316.png)

Perform a "Compare model with the database"

![2022-04-25_08-59-09](https://user-images.githubusercontent.com/772549/165045798-473425f6-ece4-4908-9c4a-2c04b2a782c2.png)

As you can see the relationships do not appear

Log files

```
09:05:38 Error occurred during schema reverse engineering. 
  Reasons can be missing rights to select from system tables or query incompatibility 
  ( view Edit / RdbmsSettings / Reverse engineering ). Inform DbSchema team using 
  Help / Technical Support.

java.sql.SQLSyntaxErrorException: (conn=1326) You have an error in your SQL syntax; 
  check the manual that corresponds to your MariaDB server version for the right syntax 
  to use near '-gateway' at line 1
  at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:270)
```

**Comment by wise-coders** [comment]
Thank you for writing about this. The issue will be fixed right tomorrow. On Wednesday morning a beta update will be available under https://dbschema.com/beta.php
The version number will be the same, the build number will increase.

**Comment by rippo** [comment]
Thanks I can confirm this now works using build `220425`
