### ISSUE TITLE
In the git function, languages ​​other than English are broken.

### ISSUE THREAD

**Issue by hdayj** [wise-coders/dbschema#68]
Hello.

In the git function, languages ​​other than English are broken.
My version is 8.5.0.

Thank you.

**Comment by wise-coders** [comment]
Could you please add a screenshot? I am not sure what is wrong there, maybe is an encoding issue. It would help us to understand the problem

**Comment by hdayj** [comment]
![dbschema git function issue](https://user-images.githubusercontent.com/104423943/165416949-bc5cd3fa-eed5-4946-b0a3-56df609001d6.png)

**Comment by hdayj** [comment]
I am writing Korean in the comments, but the value of the right git project is broken. However, if you actually open the file with an editor, it looks good. Some information on the left was erased as company information.

Thank you.

**Comment by wise-coders** [comment]
Soon we will release a new version. Please let me know if this works fine. I think is an encoding issue by reading the file, and we just fixed something similar.
