### ISSUE TITLE
API generate PDF instead of html

### ISSUE THREAD

**Issue by briffle** [wise-coders/dbschema#7]
2. Please include the DbSchema version, operating system and used database
DbSchema 8.2.7 Ubuntu 19.10 and postgresql

3. The steps to reproduce this issue
I see in your documentation (https://dbschema.com/documentation/automation-api.html) how to load project, and generate HTML documentation from the API examples, ( layout.generateHtmlDocumentation(htmlFile, true, true) )however, I don't see a method in your API for generating the PDF documentation.  In the UI, we can generate a PDF.  

Is there a way to automatically create the PDF documentation?

**Comment by wise-coders** [comment]
In next automatic release we will add similar 
`layout.generatePdfDocumentation(htmlFile, true, true) `
