### ISSUE TITLE
Can I Show Table Description Text in Layout Diagram ? 

### ISSUE THREAD

**Issue by ylyxf** [wise-coders/dbschema#72]
in some case, the table name is very obscure ，if i can show the table's description text in layout diagram , the diagram's expressive ability will more powerful 。(the table's onhover feature may too difficult to show all table's description  text  without move mouse )

![image](https://user-images.githubusercontent.com/3871920/174927009-f21e6e65-4e0b-42f6-a6e0-eca9d2f37ba2.png)

![image](https://user-images.githubusercontent.com/3871920/174927325-35dd62fb-afa7-4a13-95be-1fbc3a64012a.png)

![image](https://user-images.githubusercontent.com/3871920/174927699-92152a2e-748c-4ac0-ae40-f6930f56b9f9.png)

**Comment by wise-coders** [comment]
We show the description as mouse-over tooltip. The description can be a long text, sometimes multiline. This won't work in the diagram.

**Comment by wise-coders** [comment]
We show the description as mouse-over tooltip. The description can be a long text, multi-line. Showing it in the diagram won't work.
