### ISSUE TITLE
DbShell Download

### ISSUE THREAD

**Issue by MichalisDBA** [wise-coders/dbschema#73]
Hello.

Sorry to asking here but where can i download DbShell.

I can not find it anywhere in your official site.

Thank you.

**Comment by wise-coders** [comment]
Here is it: 
https://dbschema.com/download/dbshell/dbshell.exe
https://dbschema.com/download/dbshell/dbshell.dmg
https://dbschema.com/download/dbshell/dbshell.sh
https://dbschema.com/download/dbshell/dbshell.rpm
https://dbschema.com/download/dbshell/dbshell.zip

The interest in this product was too low , therefore we removed the pages from the website. Probably one page was still referred in Google. Is this right, have you found it in Google?
Please write us feedback about it, and we will consider including it in the DbSchema package.

**Comment by MichalisDBA** [comment]
Thank you very much. Yes i found it in Google search. I was going to use usql project and then found yours. I hope it supports Oracle 9i. We have some legacy systems and want to automate some procedures until we migrate to newer versions of Oracle. Will try it as soon as possible and hope we purchase a license too. Thank you.
