### ISSUE TITLE
Simple Data Dictionary Needed without Layouts/Diagrams

### ISSUE THREAD

**Issue by ShekharSiyer** [wise-coders/dbschema#76]
### Simple Data Dictionary Needed without Layouts/Diagrams ###
Hello! 
**Requirement**: We need a simple Data Dictionary of Table & Column Names and Descriptions (in a SQL Server Database). No need, yet, for the Diagrams in the Layouts.
**Issue with DbSchema** :  (a) Cannot close all the Layouts; the last Layout remains Open/Active even when we do not want it. (b) In the Documentation Generation window, there is no option to leave out all the Layouts!

**Solution Needed**: We need to be able to close all the Layouts and we need to be able to leave out Layouts when we generate Documentation, please.

**Comment by wise-coders** [comment]
Please use Layout / Export HTML5 documentation.
There you can deactivate the option 'Diagram image' and you will get only the text description.
