### ISSUE TITLE
Jdbc driver for influxdb

### ISSUE THREAD

**Issue by mehrdad2000** [wise-coders/dbschema#77]
Hi as i read this [link](https://dbschema.com/jdbc-driver/InfluxDB.html) there is driver for connecting to influxdb, but i have two questions:

1-AFAIK "ifxjdbc.jar" belong to informix driver NOT influxdb dirver! in link that you mention write that: “Required File(s): ifxjdbc.jar”, why?

2-there is no “Java Driver Class: com.dbschema.influxdb.InfluxJdbcDriver” in zip file.

**Comment by wise-coders** [comment]
The webpage is now fixed. The class is com.wisecoders.dbschema.influxdb.JdbcDriver

**Comment by mehrdad2000** [comment]
@wise-coders thanks, after retry got this error:

2022-07-21 11:54:17.730 +0430  [dw-66 - POST /api/connections/status] ERROR io.dropwizard.jersey.errors.LoggingExceptionMapper - Error handling a request: 99104a48e2c6038b
java.lang.NoSuchMethodError: java.net.URLDecoder.decode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String;
        at com.wisecoders.dbschema.influxdb.JdbcDriver.connect(JdbcDriver.java:62)

**Comment by wise-coders** [comment]
We deployed a new driver on our website.
The language level increased to Java 10. This was the issue.
