### ISSUE TITLE
Save File doesn't actually save .sql files

### ISSUE THREAD

**Issue by Clamatius** [wise-coders/dbschema#78]
**1) Please check DbSchema Help / Output logs for errors.**

Alas, nothing except I suppose it does show that Save File has been selected.

17:45:05 > saveFile
17:45:08 > outputLogs
17:45:08 Dialog Output Logs

**2) Please include the DbSchema version, operating system and used database**

DBSchema 9.0.2 build 220623
OS X
DB: Google Cloud Spanner

**3) The steps to reproduce this issue**

1. Open SQL file from initial Start New Project dialog
2. Select file from file dialog and click Open
3. Click "OK" on the Parse Script dialog
4. Edit SQL file - e.g. add a comment
5. Select File -> Save File
6. Dialog pops up as per the save as option (this is already wrong, why not save as the file you already opened?)
7. Enter original filename and click "Save"
8. Click "Replace" on the confirmation dialog
9. File has not actually been saved
10. Edit SQL file
11. Select File -> Save File
12. No "save as" dialog this time, it just acts like it saved it. But it didn't.

There is a workaround - if you use Save As instead, it does save the file, but that is very annoying because you have to enter the file name every time.

EDIT: I just updated to 9.0.3 and this helps a lot. Now in step 9 above it has actually saved the file and in step 12 it did too. Still prompts to replace the file the first time as if you picked Save As though (step 6), which is annoying.

**Comment by wise-coders** [comment]
Thank you for writing about this. This issue will be fixed in the next minor release.
