### ISSUE TITLE
Suggestion: Assign Group to Table Externally

### ISSUE THREAD

**Issue by NeilN1** [wise-coders/dbschema#81]
It's be helpful if I could:

1. Export a list of tables on the current layout and their groups to a text file
2. Allow someone else to edit the group assigned to each table
3. Import the text file which would update table groups and auto-arrange the diagram accordingly.

**Comment by wise-coders** [comment]
Why should you do this using a text file, instead of doing it directly visual in DbSchema? I need to understand this feature request.

**Comment by NeilN1** [comment]
If you have many tables, it may be better for business analysts (who don't have access to the tool, only exported diagrams) to decide what groups to have and which group each table belongs to rather than the DBA.

**Comment by wise-coders** [comment]
I suggest two solutions here:
1. let the business analyst also use DbSchema, without database connectivity. They can work on the model file.
2. Use automation scripts to implement custom logic. Check Tools / Automation scripts using Java.
