### ISSUE TITLE
Suggestion: Add shortcut keys for moving a column up/down

### ISSUE THREAD

**Issue by NeilN1** [wise-coders/dbschema#85]
In the table editor can shortcut keys be added to the up/down buttons?  New columns are added to the bottom (an insert option would be nice) and it may take 20-30 clicks to move it into the proper display position.

![image](https://user-images.githubusercontent.com/12532256/203380579-c8e0bddc-cd78-4e03-a699-c58f7718fa02.png)

**Comment by wise-coders** [comment]
Now is possible to press the ALT key and the underlined letter on the button.
This is activating the HotKey mode. Press Alt again to deactivate.
