### ISSUE TITLE
Snowflake views ddl come empty

### ISSUE THREAD

**Issue by paddelia** [wise-coders/dbschema#86]
2. Please include the DbSchema version, operating system and used database
 Downloaded a couple days ago

3. The steps to reproduce this issue
Connect to a snowflake db

4. Views are not coming across, the columns is 0 and the definition is empty.

I may have to do something else to retrieve views ddl may be?
![image](https://user-images.githubusercontent.com/104227974/203639511-5b8b6d2d-9a7f-434a-bcb7-dc9ce44e2315.png)

**Comment by wise-coders** [comment]
Thank you for reporting this issue.
We tried to reproduce this, but we got a different issue.
We are using this query to load the view definition:
SELECT table_name, view_definition FROM "${catalog}".INFORMATION_SCHEMA.views WHERE table_schema='${schema}'


When I execute this from the SQL Editor, I get an 
No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

I use a Snowflake trial account, which does not have any warehouse.

Could you please try to test this query for us?
