### ISSUE TITLE
Key in License Information

### ISSUE THREAD

**Issue by robertallitsch** [wise-coders/dbschema#88]
I've entered by name as Registration Name and cut and paste of license information (including the ###), but still get the error:

Wrong Registration Name or invalid Key...   Where can I find the Registration Name or do I need to uninstall the software and reinstall?

![image](https://user-images.githubusercontent.com/52826350/207112590-f0a0c5ab-f53d-4419-a4cc-980f8d6c8dd1.png)

![image](https://user-images.githubusercontent.com/52826350/207112742-22dd24c1-5f77-4695-bc4b-25513652e17c.png)

**Comment by wise-coders** [comment]
The kit you try to install is very old. Please download from DbSchema.com

**Comment by wise-coders** [comment]
That version did work with different registration keys. The current version does not need a registration name.
