### ISSUE TITLE
Looking for Collaboration 

### ISSUE THREAD

**Issue by imvetri** [wise-coders/dbschema#89]
Hello,

I'm name is Vetri. I recently came across your designer tool and I thought I could reach out to you to collaborate on building full stack application designer 

I have a concept built called ui-editor and you can have a look at it here https://github.com/imvetri/ui-editor

Looking forward to hearing from you.

Thanks.

**Comment by wise-coders** [comment]
What does a full stack application designer mean? Could you please give more details?

**Comment by imvetri** [comment]
![Full stack application designer](https://user-images.githubusercontent.com/6542274/211247691-3e3462ad-aaf6-4053-95b7-da3a1b2d9adf.png)

**Comment by Psyclo1** [comment]
imvetri, it looks like you are asking for an enterprise architecture tool, one that spans multiple areas.  There are tools that model business processes (BPMN), application objects (UML), data design (CDM, LDM, PDM), organizational, physical locations, etc.  When boiled down, a model is simply a collection of objects with various properties interconnected with each other and displayed on a number of diagrams to aid in communicating the underlying complexity of the thing being modeled.  Of course the different models relate to each other, so a data object could link to processes, application objects, data stewards, etc.  Being able to model everything would be extremely valuable.  However, it is a huge stretch for any software development company to biuld a solid tool in that space, as there are a number of very established companies already there.
For instance, Sparx Systems Enterprise Architect, Bizzdesign Enterprise Studio, Erwin Evolve, UNICOM System Architect and finally PowerDesigner.
