### ISSUE TITLE
Error on creating primary keys (at least for Oracle)

### ISSUE THREAD

**Issue by mtuxgu** [wise-coders/dbschema#91]
DbSchema-Version: 9.2.0 (221214)
OS: Windows (Server 2019)

When creating a primary key and just selecting "Primary Key" in New-Column-Dialog DbSchema does not create a primary key but field with a unique index.

![grafik](https://user-images.githubusercontent.com/14185766/212619120-b6ebe3f2-ecdf-40f9-90c4-457aeaebd589.png)

![grafik](https://user-images.githubusercontent.com/14185766/212619283-391685b8-553d-48d2-a3c1-2db4af88879d.png)

To get a "real" primary key you need to first hit "Mandatory" and then "Primary Key".

What i find the most struggling part of this issue:
DbSchema claims to create a primary key until you close the Edit-Table-Dialog and reopen it. 

BR
Markus

**Comment by wise-coders** [comment]
May I ask, which database do you use? I think is a database-related issue.
Are you connected to the database or working offline?

**Comment by mtuxgu** [comment]
It is an Oracle Schema and I am working offline.

**Comment by wise-coders** [comment]
Thank you for your reply. This will be fixed in the next minor release.
