### ISSUE TITLE
Logical to Physical Naming conversions not always working

### ISSUE THREAD

**Issue by mrneals** [wise-coders/dbschema#93]
1. Please check DbSchema Help / Output logs for errors.

2. Please include the DbSchema version, operating system and used database 9.2.1 Windows

4. The steps to reproduce this issue
I set the naming standards to convert spaces to underscores as well as converting logical names to their abbreviations. It works on some Entities and Attribute conversions but not all! Even when the same word is used.

**Comment by wise-coders** [comment]
Can you please send us a sample model file to test? Please let me know which entities/attributes are not working fine.

**Comment by mrneals** [comment]
I have provided Logical, Physical, and naming conversion files. So in the physical, I want underscores where the spaces were in the logical name. Also, all words should use the conversion xml, correct? Let me know your thoughts, thanks.


Neal Seidlitz410-736-2562 

    On Monday, February 6, 2023 at 01:14:05 AM EST, Wise Coders ***@***.***> wrote:  
 
 


Can you please send us a sample model file to test? Please let me know which entities/attributes are not working fine.

**Comment by wise-coders** [comment]
I didn't got any files. Have you sent via email? 
Our tests works fine, that's why I ask for help to reproduce this issue. I need to see in which context and where the replace didn't work. Also some screenshots would help.

**Comment by mrneals** [comment]
Yes, I attached to the last email.


Sent from Yahoo Mail for iPhone


On Monday, February 6, 2023, 12:55 PM, Wise Coders ***@***.***> wrote:




I didn't got any files. Have you sent via email?
Our tests works fine, that's why I ask for help to reproduce this issue. I need to see in which context and where the replace didn't work. Also some screenshots would help.

**Comment by wise-coders** [comment]
The tread is running in github, and here I see no files.
Could you please send the files to our support email from the website ( please include also the issue text ).

**Comment by mrneals** [comment]
When I try to attach the files I get an error saying "We don't support that file type" Is there another way to attach or send the files?

**Comment by wise-coders** [comment]
By email at support at dbschema.com

**Comment by mrneals** [comment]
I have attached the latest files. Please note how some logical names are translated correctly, and others are not. Some physical names get underscores where the spaces were in the logical name, yet some still have spaces.


Neal Seidlitz 

    On Wednesday, February 8, 2023 at 05:42:25 AM EST, Wise Coders ***@***.***> wrote:  
 
 


By email at support at dbschema.com

**Comment by wise-coders** [comment]
A new beta update has been deployed:
https://dbschema.com/beta.php
Please let me know if this works as expected.
