### ISSUE TITLE
MySQL Character Limitation for Foreign Key Names: Request for Feature to Customize Naming Pattern

### ISSUE THREAD

**Issue by bcerquiare** [wise-coders/dbschema#94]
MySQL has a character limit for foreign key names. It would be very helpful if your software allowed us to customize the automatic naming pattern for foreign keys, as it can be difficult to correct these names once we have created a document with many tables. We suggest adding this feature to improve the usability of your product

DBSchema Version: 
DbSchema 9.2.1 build 230125 OpenJRE 17.0.6

Reproduction: 
Using MySQL, create two tables with long names and create a relationship between them. The suggested name for the foreign key will be longer than the limit allowed by MySQL

**Comment by wise-coders** [comment]
Thank you for writing about this. This will be fixed in the next release.
