### ISSUE TITLE
utf-8 (utf8mb3_general_ci) characterset- Persian language not shown correctly in comment and table data

### ISSUE THREAD

**Issue by morrteza** [wise-coders/dbschema#95]
![utf8](https://user-images.githubusercontent.com/45652694/220013956-ec1fdedd-9a22-4bc2-ada4-6b9aba241882.png)

DBSchema version = 9.2.1 build 230128
operating system = macOS 
database = mysql 8
Default collation: utf8mb3_general_ci
Default characterset: utf8mb3

when i typing Persian language in comment or data in table , not shown correctly .

**Comment by wise-coders** [comment]
This is happening for new created tables as well, right? I mean before creating the table in the database, when you enter the comment for the first time, it is already displayed wrong? Or this happens on an already existing table, reversed engineer from the database?

**Comment by morrteza** [comment]
Yes, this also happens to newly created tables, that is, when I type Persian in the comment or in the data of the table, this happens. While the same data entered in similar software ( MYSQL Workbench) is displayed correctly.

**Comment by wise-coders** [comment]
Does this happen in the other dialogs as well, for example if you type some comment in a schema dialog ( right-click a schema and Edit)?

**Comment by morrteza** [comment]
![utf8-2](https://user-images.githubusercontent.com/45652694/220027771-239e9d9c-4587-487d-8014-63f8be25e714.png)
 not shown correctly .

**Comment by wise-coders** [comment]
Thank you very much for your help.
This seems to be a JavaFX issue. We will search if is any flag we can add to make it work correctly.

**Comment by morrteza** [comment]
Thank you.

**Comment by wise-coders** [comment]
Could you please check if this issue is fixed in the latest release 9.4.2?
I close the ticket. If the issue persists, please reopen.

**Comment by morrteza** [comment]
DBSchema version = 9.4.2 build 231003
![002](https://github.com/wise-coders/dbschema/assets/45652694/37f09fb9-dd97-44d0-9b82-faeb63b37ffc)

operating system = macOS
database = mysql 8
Default collation: utf8mb3_general_ci
Default characterset: utf8mb3

when i typing Persian language in comment or data in table , not shown correctly .

**Comment by morrteza** [comment]
![002](https://github.com/wise-coders/dbschema/assets/45652694/e141a278-f123-4c9c-aa09-470b1c1c5ef6)

DBSchema version = 9.4.2 build 231003
operating system = macOS
database = mysql 8
Default collation: utf8mb3_general_ci
Default characterset: utf8mb3

when i typing Persian language in comment or data in table , not shown correctly .

**Comment by wise-coders** [comment]
Can you please add this to DbSchema.vmoptions ( located in the same folder as DbSchema.exe ? 
-Djdk.gtk.version=2

The vmoptions file is located in
./DbSchema.app/Contents/vmoptions.txt on the MacOs.

**Comment by morrteza** [comment]
![003](https://github.com/wise-coders/dbschema/assets/45652694/3e47f060-de0b-476f-be9b-61fff38dba62)
![004](https://github.com/wise-coders/dbschema/assets/45652694/f8ffc5ad-5d8d-4310-9490-ea1626482d93)
![005](https://github.com/wise-coders/dbschema/assets/45652694/46ba1a40-410a-41f7-bf9d-1e83aeedd4bb)


not working .

**Comment by morrteza** [comment]
![003](https://github.com/wise-coders/dbschema/assets/45652694/11d8d63e-09dd-4e20-bd4a-2cd237291ff8)
![004](https://github.com/wise-coders/dbschema/assets/45652694/c83ba3ae-571c-4e8c-a650-49f0cd4d92ee)
![005](https://github.com/wise-coders/dbschema/assets/45652694/77e82d8a-6e90-4f7b-8d60-334d57ce3912)

Not work .
