### ISSUE TITLE
No way how to set printer margin 

### ISSUE THREAD

**Issue by DcPublished** [wise-coders/dbschema#97]
1. Please check DbSchema Help / Output logs for errors.
When printing model prints fine except that the borders at least 1" wide.   This is a massive waste of space forcing the data model to be much smaller than necessary.   This makes it harder to read.

2. Please include the DbSchema version, operating system and used database
DBSchema:  V9.2.2 build 230228   
OS: MacOS V13.2.2
DB: PostgresSQL V15

3. The steps to reproduce this issue
Create model.  
Print model

**Comment by wise-coders** [comment]
In the Print dialog, choosing the Page Setup, the margins can be changed. The default values are the one used by the operating system and Java. We will try to reduce this values. Does it work fine for you to modify the margins from this dialog?
![image](https://user-images.githubusercontent.com/60284259/222884062-d7a9e577-8d7c-416b-9875-d0c03a7ab4d0.png)
