### ISSUE TITLE
load_values_from_pk in Data Generator

### ISSUE THREAD

**Issue by NeilN1** [wise-coders/dbschema#98]
How do I use load_values_from_pk as a pattern in the data generator? I've confirmed the FK exists and have the following but it's obviously not picking up values from the PK table (SQL Server, latest version of DbSchema).

![image](https://user-images.githubusercontent.com/12532256/224800032-894ffaec-df68-4a3e-9067-1025622d8cfd.png)

**Comment by NeilN1** [comment]
Ok figured out the sample is not a live preview. One small issue: Generating data directly into the db works fine but generating SQL scripts generates true/false for bit fields which SQL Server doesn't like:

Invalid column name 'false'.

**Comment by wise-coders** [comment]
Issue will be solved right this week. The [beta update](https://dbschema.com/beta.php) from next week will get the fixes for both issues ( fk generator and bit fields ).
