### ISSUE TITLE
Collation issue

### ISSUE THREAD

**Issue by aplaxas** [wise-coders/dbschema#99]
Dear,
I am evaluating DbSchema in order to replacing current ER Tools(ModelRight), because I like DbSchema's Git features.

I tested it on Windows/SQL Server 2019/Production&Development DBs
1. Create DbSchema from production database
2. Compare the schema with development database, which was restored from Production DB 
3. Always showing Collate different
   ALTER TABLE xxxxx ALTER COLUMN TableName nvarchar(128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL;

**Comment by wise-coders** [comment]
For MySql we reverse engineer the table definition by running 'SHOW CREATE TABLE...'.
From Model / Settings /Reverse engineer you can set to log the DDL parser statements to Help / Output logs.
It could be that you have to merge the collation one time in the model.
Eventually, we can think a way to remove the collation during reverse engineer, but this may be not the best.
